# Generated by Django 4.1.2 on 2022-10-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
