# Generated by Django 4.1.2 on 2022-10-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('List', '0003_alter_todolist_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
